### PR TITLE
Adding C++ code for merge two sorted linked lists

### LINKED ISSUE #10: Add Code for Any Question Related to Linked List Data Structure
Please go through the [rules](https://github.com/sigma3labs/Sigma3-DSA-Marathon/blob/main/CONTRIBUTING.md) from the repository before making any PR📝

**In our repo we are accepting only One PR from each participant so if you are assigned for a task previously int this repo then please do not ask to assign yourself again** 🙂

Also mention the language in which you want to add code 👨‍💻

Other maintainers:- @rajdeep-ghosh @DEBADYUTI-KARMAKAR 

Keep contributing !

### PR DESCRIPTION
**Pull request by SulagnaKundu**
##What does this PR do?
This PR adds a C++ code for merging two sorted linked lists.

fixes #10

### CODE REVIEW

**Review by DEBADYUTI-KARMAKAR — CHANGES_REQUESTED** [review]
Remove unnecessary file.

**Comment by SulagnaKundu** [comment]
I made the requested changes . Please review the changes

**Review by DEBADYUTI-KARMAKAR — CHANGES_REQUESTED** [review]
commit only .cpp file

**Comment by SulagnaKundu** [comment]
Please review the changes made.

**Review by DEBADYUTI-KARMAKAR — APPROVED** [review]

**Pull request merged**
