### PR TITLE
added the code of parenthesis checking

### PR DESCRIPTION
**Pull request by divyan7982**

### CODE REVIEW

**Comment by lucy2512** [comment]
Please read the contribution.md file before making any PR!

**Comment by divyan7982** [comment]
> Please read the contribution.md file before making any PR!

i have not updated the code in my first commit by mistakenly so i have committed again with updated code.

**Comment by lucy2512** [comment]
bro add this code inside the leetcode/C++ folder .

**Comment by divyan7982** [comment]
I have added the code as you said bro.

**Pull request closed without merging**
